export const styles = {
  clueNumber: {
    color: '#1e75e9',
    fontSize: '0.75rem',
    left: '0.25rem',
    position: 'absolute',
    top: '0.25rem',
    zIndex: '3',
  },
  crosswordSettings: {
    backgroundColor: 'orange',
    width: '4rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
  currentSquare: {
    backgroundColor: '#7590c1',
    caretColor: 'transparent',
    fontSize: '2rem',
    height: '3rem',
    outline: 'solid black 1px',
    position: 'relative',
    textAlign: 'center',
    textTransform: 'capitalize',
    width: '3rem',
    zIndex: '2',
  },
  row: {
    border: 'none',
    display: 'flex',
    flexDirection: 'row',
  },
  square: {
    backgroundColor: '#cfdee8',
    caretColor: 'transparent',
    fontSize: '2rem',
    height: '3rem',
    outline: 'solid black 1px',
    borderTop: 'none',
    borderBottom: 'none',
    borderLeft: 'none',
    borderRight: 'none',
    position: 'relative',
    textAlign: 'center',
    textTransform: 'capitalize',
    width: '3rem',
    zIndex: '2',
  },
  squareVictory: {
    backgroundColor: 'lightGreen',
    caretColor: 'transparent',
    fontSize: '3rem',
    height: '3rem',
    outline: 'solid black 1px',
    borderTop: 'none',
    borderBottom: 'none',
    borderLeft: 'none',
    borderRight: 'none',
    position: 'relative',
    textAlign: 'center',
    textTransform: 'capitalize',
    transform: 'rotate(360deg)',
    transition: '1s',
    userSelect: 'none',
    width: '3rem',
    zIndex: '2',
  },
  squareWrapper: {
    position: 'relative',
  },
};
