export const styles = {
  clue: {
    textAlign: 'left',
  },
  clueNumber: {
    color: 'gray',
    fontSize: '0.75rem',
    left: '0.25rem',
    position: 'absolute',
    top: '0.25rem',
    zIndex: '3',
  },
  cluesBox: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    width: '32rem',
  },
  crosswordSettings: {
    backgroundColor: 'orange',
    width: '4rem',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-evenly',
  },
  currentSquare: {
    backgroundColor: 'cyan',
    caretColor: 'transparent',
    fontSize: '2rem',
    height: '3rem',
    outline: 'solid black 1px',
    position: 'relative',
    textAlign: 'center',
    textTransform: 'capitalize',
    width: '3rem',
    zIndex: '2',
  },
  gridAndSettings: {
    display: 'flex',
    flexDirection: 'row',
  },
  main: {
    height: '80vh',
    color: 'white',
    display: 'flex',
    justifyContent: 'space-between',
  },
  row: {
    display: 'flex',
    flexDirection: 'row',
  },
  section: {
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
    justifyContent: 'center',
  },
  square: {
    backgroundColor: 'white',
    caretColor: 'transparent',
    fontSize: '2rem',
    height: '3rem',
    outline: 'solid black 1px',
    borderTop: 'none',
    borderBottom: 'none',
    borderLeft: 'none',
    borderRight: 'none',
    position: 'relative',
    textAlign: 'center',
    textTransform: 'capitalize',
    width: '3rem',
    zIndex: '2',
  },
  squareVictory: {
    backgroundColor: 'lightGreen',
    caretColor: 'transparent',
    fontSize: '3rem',
    height: '3rem',
    outline: 'solid black 1px',
    borderTop: 'none',
    borderBottom: 'none',
    borderLeft: 'none',
    borderRight: 'none',
    position: 'relative',
    textAlign: 'center',
    textTransform: 'capitalize',
    transform: 'rotate(360deg)',
    transition: '1s',
    userSelect: 'none',
    width: '3rem',
    zIndex: '2',
  },
  squareWrapper: {
    position: 'relative',
  },
  title: {
    color: 'white',
  },
};
