export const styles = {
  row: {
    display: 'flex',
    flexDirection: 'row',
    color: 'red',
  },
  square: {
    backgroundColor: 'white',
    caretColor: 'transparent',
    fontSize: '2rem',
    height: '3rem',
    outline: 'solid black 1px',
    textAlign: 'center',
    textTransform: 'capitalize',
    width: '3rem',
  },
  squareVictory: {
    backgroundColor: 'lightGreen',
    caretColor: 'transparent',
    fontSize: '3rem',
    height: '3rem',
    outline: 'solid black 1px',
    textAlign: 'center',
    textTransform: 'capitalize',
    transform: 'rotate(360deg)',
    transition: '1s',
    userSelect: 'none',
    width: '3rem',
  },
  currentSquare: {
    backgroundColor: 'cyan',
    caretColor: 'transparent',
    fontSize: '2rem',
    height: '3rem',
    outline: 'solid black 1px',
    textAlign: 'center',
    textTransform: 'capitalize',
    width: '3rem',
  },
  main: {
      height: '80vh',
  },
  title: {
      color: 'red',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    height: '100%',
  },
};
